### ISSUE TITLE
double numbers in lists

### ISSUE THREAD

**Issue by weasel25** [azate/anti-random.org#6]
the selection for the list works well except that it creates a double number.

IE if the list were:
1
2
3
and you chose 2 it may finish and show
2
2
3
or 
2
1
2

any way to keep the numbers from doubling?

**Comment by hz61p1** [comment]
Could you please attach a video or gif of the bug demonstration?

**Comment by weasel25** [comment]
Here is a video. First click is normal left click. Second is right click

**Comment by weasel25** [comment]
https://user-images.githubusercontent.com/108029111/175384739-1946ce76-95cb-4bcc-ab57-9be02588fd12.mov

**Comment by weasel25** [comment]
> Could you please attach a video or gif of the bug demonstration?

**Comment by weasel25** [comment]
Weird.

**Comment by weasel25** [comment]
Oh man. Sorry my phone loves to close this for some reason

**Comment by Atomicairps** [comment]
I’m having this same issue. Would happily send some btc for a fix

**Comment by hz61p1** [comment]
Please check the latest release
