### ISSUE TITLE
does it work atm?

### ISSUE THREAD

**Issue by thenewmexico** [azate/anti-random.org#8]

**Comment by hz61p1** [comment]
You are trying to add an unbuilt extension to Chrome. You have to build it yourself or download it from the release section following the instructions in the manual

**Comment by hz61p1** [comment]
If we rely on
`
Archivio
~/Scrivania/anti-random.org-master/src
`
You download the sources via Code -> Download ZIP and not the ready-made releases as described in the manual

**Comment by pushthiswave** [comment]
thank you man!
