### ISSUE TITLE
Extension delay replace result

### ISSUE THREAD

**Issue by hinotme** [azate/anti-random.org#9]
Looks like randomorg has changed a lot.
Today I used the extension and found that there is a delay.
I found that random org returns results first and it takes about 1 second after extension to overwrite new expected results.

**Comment by thenewmexico** [comment]
I’m also interested about this extension. I think that this problem must be fixed in the new version

**Comment by hz61p1** [comment]
Can you provide more details?
How big is the list?
Share a screencast with a demonstration

**Comment by thenewmexico** [comment]
could i send you all the files and infos about the little bugs that i found via email?

**Comment by hz61p1** [comment]
@thenewmexico Did you send it? I haven't received anything yet.

**Comment by thenewmexico** [comment]
> 

No, I didn’t sorry. I’ve never opened the computer since Easter holidays. Could you please give me your email btw? Best regards

**Comment by hz61p1** [comment]
@thenewmexico  purgamentum@protonmail.com

**Comment by hz61p1** [comment]
@hinotme Can you confirm the existence of this problem in the current time? @thenewmexico said in private correspondence that he no longer observes this problem.

**Comment by hz61p1** [comment]
@hinotme I'm waiting for an answer, if not I'll close the issue
